CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID UNIQUE                             NOT NULL,
    created_at TIMESTAMP                               NOT NULL,
    updated_at TIMESTAMP                               NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    mobile     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);