CREATE TABLE property
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid            UUID                                    NOT NULL,
    created_at      TIMESTAMP                               NOT NULL,
    updated_at      TIMESTAMP                               NOT NULL,
    address         VARCHAR(255)                            NOT NULL,
    description     VARCHAR(255)                            NOT NULL,
    rooms           INT                                     NOT NULL,
    price_per_night DECIMAL                                 NOT NULL,
    CONSTRAINT pk_property PRIMARY KEY (id)
);