CREATE TABLE payment_method
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID                                    NOT NULL,
    created_at  TIMESTAMP                               NOT NULL,
    updated_at  TIMESTAMP                               NOT NULL,
    card_number VARCHAR(255)                            NOT NULL,
    cvc         VARCHAR(255)                            NOT NULL,
    expiry_date VARCHAR(255)                            NOT NULL,
    last4       VARCHAR(255)                            NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_paymentmethod PRIMARY KEY (id)
);

ALTER TABLE payment_method
    ADD CONSTRAINT FK_PAYMENTMETHOD_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);