CREATE TABLE booking
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID                                    NOT NULL,
    created_at        TIMESTAMP                               NOT NULL,
    updated_at        TIMESTAMP                               NOT NULL,
    check_in_date     date                                    NOT NULL,
    check_out_date    date                                    NOT NULL,
    amount            DECIMAL                                 NOT NULL,
    status            VARCHAR(255)                            NOT NULL,
    tx_id             VARCHAR(255)                            NOT NULL,
    property_id       BIGINT                                  NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    payment_method_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_PAYMENT_METHOD FOREIGN KEY (payment_method_id) REFERENCES payment_method (id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);